# Generated by Django 4.1.4 on 2023-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprenta', '0003_mensaje_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
