# Generated by Django 4.1.4 on 2022-12-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.AlterField(
            model_name='automovil',
            name='anio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='modelo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=200),
        ),
    ]
