# Generated by Django 4.1.4 on 2022-12-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_delete_dummy_alter_automovil_año_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='año',
        ),
    ]
